// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB05DEgMezjf6TEJGLzfHMxOPJN75JMbhw',
    appId: '1:312885486902:web:ad040c5de5b350fa61ff97',
    messagingSenderId: '312885486902',
    projectId: 'chatdemo-c38e8',
    authDomain: 'chatdemo-c38e8.firebaseapp.com',
    storageBucket: 'chatdemo-c38e8.appspot.com',
    measurementId: 'G-PW6MHG2W2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAJyfVErKVJGUm3qOXqZeDGYEj0_nVMTE',
    appId: '1:312885486902:android:403d789452b52e9661ff97',
    messagingSenderId: '312885486902',
    projectId: 'chatdemo-c38e8',
    storageBucket: 'chatdemo-c38e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAltsKZBdMRpcY9axvB5UZODnKQTKM3NK8',
    appId: '1:312885486902:ios:503471ffb0276de861ff97',
    messagingSenderId: '312885486902',
    projectId: 'chatdemo-c38e8',
    storageBucket: 'chatdemo-c38e8.appspot.com',
    iosClientId: '312885486902-9annr4gqjd728umsicutar853j43r71c.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAltsKZBdMRpcY9axvB5UZODnKQTKM3NK8',
    appId: '1:312885486902:ios:503471ffb0276de861ff97',
    messagingSenderId: '312885486902',
    projectId: 'chatdemo-c38e8',
    storageBucket: 'chatdemo-c38e8.appspot.com',
    iosClientId: '312885486902-9annr4gqjd728umsicutar853j43r71c.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppDemo',
  );
}
